# Custom nav
nav:
  title: "Miao Duang"

favicon: ""

# Custom background
background:
  color: "#eff0f6"
  image: ""

# Social media
social:
  Dribbble: https://dribbble.com/MiaoDuang
  Behance: https://www.behance.net/1769627227868a2
  Zcool: https://my.zcool.com.cn/works
  Lofter: 
  Instagram: 
  # GitHub: https://github.com/MiaoChenhao

# Custom footer
mail: 17696272278@163.com
copyright: All rights reserved @Miao Duang

# Custom menu. You can specific the path or the card style (only useful for category page).
# Two kinds of card style: 'project-card', 'article-card',
# Never mind the name.
menu:
  # Project: /
  Project: /
  Works: http://www.wulihub.com.cn/go/Jm83mQ/index.html
  #Archive: /categories
#  Portfolio: /resume
  About: /about

# Specific default categories or tags of home page.
# Post which belongs to `category` or `tag` and don't belongs to `except_category` or `except_tag` will be filtered.
home:
  # set card style of home page
  tag: Blog
  # category: Project
  # tag: 算法
  # except_category: 树
  # except_tag:
  #   - 总结
  #   - css

card_style:
  home: project-card
  archive: article-card
  tag: project-card
  category: article-card

# category page
category_generator:
  category_per_page: 3
  post_per_category: 3

node_sass:
  outputStyle: nested
  precision: 5
  sourceComments: false